### ISSUE TITLE
No module named leap

### ISSUE THREAD

**Issue by Bountam** [joaquimrocha/Leap-GNOME-Controller#1]
~/Leap-GNOME-Controller-master$ leap-gnome-controller.py 
Traceback (most recent call last):
  File "/usr/bin/leap-gnome-controller.py", line 21, in <module>
    import leap
ImportError: No module named leap

**Comment by imak** [comment]
Install the LeapSDK and make sure Leap.so is in the library path, either in
LD_LIBRARY_PATH or in ldconfig -p.

**Comment by anthonylai** [comment]
Where is Leap.so?  Is it the same as libLeap.so?  I have the same issue, and it did not work for me.  Below please find the sample info.

Thanks.
Sincerely,
Anthony

/usr/lib/Leap$ echo $LD_LIBRARY_PATH/
/usr/lib/Leap/

/usr/lib/Leap$ ls
libLeap.so      libQtGui.so.4      libQtScript.so.4       libusb-1.0.so.0
libQtCore.so.4  libQtNetwork.so.4  libQtWebKit.so.4
libQtDBus.so.4  libQtOpenGL.so.4   libQtXmlPatterns.so.4

~/lib/leap-motion/LeapSDK/samples$ python Sample.py 
Traceback (most recent call last):
  File "Sample.py", line 9, in <module>
    import Leap, sys
ImportError: No module named Leap

**Comment by anthonylai** [comment]
Nvm, need to setup python path.  It is working now.  Thanks.

**Comment by joaquimrocha** [comment]
Sorry for not having answered it. I am glad all is fine now.
